version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      HOST: ${HOST}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      MODEL: ${MODEL}
      API_TOKEN: ${API_TOKEN}
      TELEGRAM_WEBHOOK_TOKEN: ${TELEGRAM_WEBHOOK_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ELEVEN_API_KEY: ${ELEVEN_API_KEY}
      ELEVEN_VOICE_ID: ${ELEVEN_VOICE_ID}
      CLOUDFLARE_R2_ACCESS_KEY_ID: ${CLOUDFLARE_R2_ACCESS_KEY_ID}
      CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
      CLOUDFLARE_R2_BUCKET_NAME: ${CLOUDFLARE_R2_BUCKET_NAME}
      CLOUDFLARE_R2_REGION: ${CLOUDFLARE_R2_REGION}
      CLOUDFLARE_R2_ENDPOINT_URL: ${CLOUDFLARE_R2_ENDPOINT_URL}
      CLOUDFLARE_R2_PUBLIC_ENDPOINT_URL: ${CLOUDFLARE_R2_PUBLIC_ENDPOINT_URL}
      DATABASE_URL: ${DATABASE_URL}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
