"""Add timestamps mixin

Revision ID: c21aebe75cc3
Revises: 10079de0a434
Create Date: 2024-07-24 15:47:14.935700

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision: str = 'c21aebe75cc3'
down_revision: Union[str, None] = '10079de0a434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    columns_users = [col['name'] for col in inspector.get_columns('users')]
    columns_message_history = [col['name'] for col in inspector.get_columns('message_history')]

    if 'created_at' in columns_users:
        op.alter_column('users', 'created_at', existing_type=sa.DateTime(), nullable=False, server_default=sa.func.now())
    else:
        op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    if 'updated_at' in columns_users:
        op.alter_column('users', 'updated_at', existing_type=sa.DateTime(), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    else:
        op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()))

    if 'created_at' in columns_message_history:
        op.alter_column('message_history', 'created_at', existing_type=sa.DateTime(), nullable=False, server_default=sa.func.now())
    else:
        op.add_column('message_history', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))

    if 'updated_at' in columns_message_history:
        op.alter_column('message_history', 'updated_at', existing_type=sa.DateTime(), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    else:
        op.add_column('message_history', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_history', 'updated_at')
    op.drop_column('message_history', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
